CREATE TABLE "admission_processes" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(), "employee_id" UUID NOT NULL, "employment_contract_id" UUID NOT NULL, "company_id" UUID NOT NULL, "checklist_template_id" UUID,
  "planned_admission_date" DATE NOT NULL, "effective_admission_date" DATE, "status" VARCHAR(20) NOT NULL DEFAULT 'DRAFT', "operational_owner" VARCHAR(160), "notes" VARCHAR(2000), "cancellation_reason" VARCHAR(500), "completed_at" TIMESTAMPTZ(6), "cancelled_at" TIMESTAMPTZ(6), "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "admission_processes_pkey" PRIMARY KEY ("id"), CONSTRAINT "admission_processes_status_check" CHECK ("status" IN ('DRAFT','IN_PROGRESS','PENDING','COMPLETED','CANCELLED'))
);
CREATE TABLE "checklist_templates" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "company_id" UUID NOT NULL, "name" VARCHAR(160) NOT NULL, "description" VARCHAR(1000), "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "checklist_templates_pkey" PRIMARY KEY ("id"), CONSTRAINT "checklist_templates_status_check" CHECK ("status" IN ('ACTIVE','INACTIVE')));
CREATE TABLE "checklist_template_items" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "checklist_template_id" UUID NOT NULL, "title" VARCHAR(160) NOT NULL, "description" VARCHAR(1000), "sort_order" INTEGER NOT NULL, "is_required" BOOLEAN NOT NULL DEFAULT true, "relative_due_days" INTEGER, "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "checklist_template_items_pkey" PRIMARY KEY ("id"));
CREATE TABLE "checklist_instances" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "admission_process_id" UUID NOT NULL, "checklist_template_id" UUID, "template_name" VARCHAR(160), "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "checklist_instances_pkey" PRIMARY KEY ("id"));
CREATE TABLE "admission_checklist_items" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "checklist_instance_id" UUID NOT NULL, "title" VARCHAR(160) NOT NULL, "description" VARCHAR(1000), "sort_order" INTEGER NOT NULL, "is_required" BOOLEAN NOT NULL DEFAULT true, "due_date" DATE, "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING', "observation" VARCHAR(1000), "completed_at" TIMESTAMPTZ(6), "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "admission_checklist_items_pkey" PRIMARY KEY ("id"), CONSTRAINT "admission_checklist_items_status_check" CHECK ("status" IN ('PENDING','IN_PROGRESS','COMPLETED','BLOCKED','NOT_APPLICABLE')));
CREATE TABLE "admission_checklist_item_history" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "admission_checklist_item_id" UUID NOT NULL, "action" VARCHAR(50) NOT NULL, "reason" VARCHAR(1000), "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "admission_checklist_item_history_pkey" PRIMARY KEY ("id"));
CREATE TABLE "admission_document_requirements" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "admission_process_id" UUID NOT NULL, "document_type" VARCHAR(160) NOT NULL, "is_required" BOOLEAN NOT NULL DEFAULT true, "receipt_status" VARCHAR(20) NOT NULL DEFAULT 'PENDING', "review_status" VARCHAR(20) NOT NULL DEFAULT 'PENDING', "received_at" TIMESTAMPTZ(6), "reviewed_at" TIMESTAMPTZ(6), "observation" VARCHAR(1000), "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "admission_document_requirements_pkey" PRIMARY KEY ("id"));
CREATE TABLE "admission_status_history" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "admission_process_id" UUID NOT NULL, "status" VARCHAR(20) NOT NULL, "reason" VARCHAR(1000), "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "admission_status_history_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "checklist_templates_company_id_name_key" ON "checklist_templates"("company_id","name"); CREATE UNIQUE INDEX "checklist_template_items_template_order_key" ON "checklist_template_items"("checklist_template_id","sort_order"); CREATE UNIQUE INDEX "checklist_instances_process_key" ON "checklist_instances"("admission_process_id"); CREATE UNIQUE INDEX "admission_checklist_items_instance_order_key" ON "admission_checklist_items"("checklist_instance_id","sort_order"); CREATE INDEX "admission_processes_contract_status_idx" ON "admission_processes"("employment_contract_id","status"); CREATE INDEX "admission_processes_company_status_idx" ON "admission_processes"("company_id","status"); CREATE INDEX "admission_checklist_items_status_due_idx" ON "admission_checklist_items"("status","due_date");
ALTER TABLE "admission_processes" ADD CONSTRAINT "admission_processes_employee_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "admission_processes_contract_fkey" FOREIGN KEY ("employment_contract_id") REFERENCES "employment_contracts"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "admission_processes_company_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "admission_processes_template_fkey" FOREIGN KEY ("checklist_template_id") REFERENCES "checklist_templates"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "checklist_templates" ADD CONSTRAINT "checklist_templates_company_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "checklist_template_items" ADD CONSTRAINT "checklist_template_items_template_fkey" FOREIGN KEY ("checklist_template_id") REFERENCES "checklist_templates"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "checklist_instances" ADD CONSTRAINT "checklist_instances_process_fkey" FOREIGN KEY ("admission_process_id") REFERENCES "admission_processes"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "admission_checklist_items" ADD CONSTRAINT "admission_checklist_items_instance_fkey" FOREIGN KEY ("checklist_instance_id") REFERENCES "checklist_instances"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "admission_checklist_item_history" ADD CONSTRAINT "admission_checklist_item_history_item_fkey" FOREIGN KEY ("admission_checklist_item_id") REFERENCES "admission_checklist_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "admission_document_requirements" ADD CONSTRAINT "admission_document_requirements_process_fkey" FOREIGN KEY ("admission_process_id") REFERENCES "admission_processes"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "admission_status_history" ADD CONSTRAINT "admission_status_history_process_fkey" FOREIGN KEY ("admission_process_id") REFERENCES "admission_processes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
